# Generated by Django 3.0.2 on 2020-11-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventDate', models.DateTimeField()),
                ('eventDescription', models.CharField(max_length=255)),
                ('hostedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount', verbose_name='host user')),
            ],
        ),
    ]
