# Generated by Django 3.0.2 on 2020-11-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natureBaseGUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animalId', models.AutoField(primary_key=True, serialize=False)),
                ('diet', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('animalType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('climate', models.CharField(max_length=255)),
                ('commonName', models.CharField(max_length=255)),
                ('latLoc', models.IntegerField()),
                ('LongLoc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scientificName', models.CharField(max_length=255)),
                ('averageHeight', models.IntegerField()),
                ('plantDescription', models.CharField(max_length=255)),
                ('fruitBearing', models.IntegerField()),
                ('lightRequirement', models.CharField(max_length=255)),
                ('waterRequirement', models.CharField(max_length=255)),
                ('leafType', models.CharField(max_length=255)),
                ('plantType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('sightID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63)),
                ('notes', models.CharField(max_length=500)),
                ('latloc', models.FloatField()),
                ('longloc', models.FloatField()),
                ('lastUpdated', models.DateTimeField()),
                ('timeRecorded', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='hostedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount'),
        ),
        migrations.CreateModel(
            name='UserSightingSaved',
            fields=[
                ('sightSaved', models.AutoField(primary_key=True, serialize=False)),
                ('savedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount')),
                ('sightingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='SightingComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2047)),
                ('postTime', models.DateTimeField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount')),
                ('onSighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Sighting')),
            ],
        ),
        migrations.AddField(
            model_name='sighting',
            name='partOfEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Event'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='sightedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount'),
        ),
        migrations.CreateModel(
            name='PlantSighting',
            fields=[
                ('sightId', models.AutoField(primary_key=True, serialize=False)),
                ('soil', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('health', models.CharField(max_length=25)),
                ('flowering', models.IntegerField()),
                ('plantType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Animal')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Location')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=6)),
                ('dangerLevel', models.IntegerField()),
                ('latLoc', models.IntegerField()),
                ('LongLoc', models.IntegerField()),
                ('type', models.IntegerField()),
                ('referenceType', models.IntegerField()),
                ('flagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumePlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Animal')),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed', to='natureBaseGUI.Animal')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='natureBaseGUI.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Event')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonalBehavior', models.CharField(max_length=255)),
                ('health', models.CharField(max_length=255)),
                ('herdSize', models.IntegerField()),
                ('animalType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Animal')),
                ('sightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natureBaseGUI.Sighting')),
            ],
        ),
    ]
